# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aaca42b6a737ba3ba1c7e6059f064e0788d88506a45363e3b95687f1a7dbdf5b8783299d2e3dcfd73c7c3406da2079bff96379d50fbf64d6a9912f96de4e172

test:
  secret_key_base: 3168834d82bf35904d2b3b5204b4e39e19834bf96eb510196b95beeb020d92b1aca99ea589c95a3a4b5973dfcae35202d605a264a8d78dcf60de989ad331a6d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
